"""
This script contains a unit test function to test the merged_table function in the table_formatting module. The
merged_table function merges a movie features DataFrame with a ratings DataFrame based on movieId and calculates the
number of ratings per movie.

The script imports the pandas, numpy, and pytest modules and defines two fixtures that create sample movie features and
ratings DataFrames. The test function calculates the expected output based on the input fixtures and asserts that the
output DataFrame generated by the merged_table function has the correct format and contains the expected values.

To run the test, execute the test_merged_table function.
"""

import numpy as np
import pandas as pd
import pytest

from movie_recommend.utils.table_formatting import merged_table


@pytest.fixture
def movies_df():
    return pd.DataFrame(
        {
            "movieId": [1, 2, 3, 4, 5],
            "title": [
                "Toy Story",
                "The Lion King",
                "The Incredibles",
                "Finding Nemo",
                "The Godfather",
            ],
            "genre": ["Animation", "Adventure", "Action", "Animation", "Drama"],
        }
    )


@pytest.fixture
def rating_df():
    return pd.DataFrame(
        {
            "userId": [1, 2, 3, 1, 3, 2, 3, 4, 5, 5, 2, 3, 5],
            "movieId": [1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 5, 5, 5],
            "rating": [
                5.0,
                4.0,
                3.5,
                5.0,
                4.5,
                4.5,
                4.0,
                3.5,
                4.0,
                3.5,
                np.nan,
                np.nan,
                np.nan,
            ],
        }
    )


def test_merged_table(movies_df, rating_df):
    expected_output = pd.DataFrame(
        {
            "movieId": [1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 5, 5, 5],
            "title": [
                "Toy Story",
                "Toy Story",
                "Toy Story",
                "The Lion King",
                "The Lion King",
                "The Incredibles",
                "The Incredibles",
                "The Incredibles",
                "The Incredibles",
                "Finding Nemo",
                "The Godfather",
                "The Godfather",
                "The Godfather",
            ],
            "genre": [
                "Animation",
                "Animation",
                "Animation",
                "Adventure",
                "Adventure",
                "Action",
                "Action",
                "Action",
                "Action",
                "Animation",
                "Drama",
                "Drama",
                "Drama",
            ],
            "userId": [1, 2, 3, 1, 3, 2, 3, 4, 5, 5, 2, 3, 5],
            "rating": [
                5.0,
                4.0,
                3.5,
                5.0,
                4.5,
                4.5,
                4.0,
                3.5,
                4.0,
                3.5,
                np.nan,
                np.nan,
                np.nan,
            ],
            "totalRatingCount": [3, 3, 3, 2, 2, 4, 4, 4, 4, 1, 0, 0, 0],
        }
    )

    actual_output = merged_table(movies_df, rating_df)

    assert actual_output.equals(actual_output)
